package com.doorstop.liz.arrivalnotifier;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.doorstop.liz.arrivalnotifier.GeofenceModel;
import com.doorstop.liz.arrivalnotifier.GeofenceSms;

import com.doorstop.liz.arrivalnotifier.GeofenceModelDao;
import com.doorstop.liz.arrivalnotifier.GeofenceSmsDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig geofenceModelDaoConfig;
    private final DaoConfig geofenceSmsDaoConfig;

    private final GeofenceModelDao geofenceModelDao;
    private final GeofenceSmsDao geofenceSmsDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        geofenceModelDaoConfig = daoConfigMap.get(GeofenceModelDao.class).clone();
        geofenceModelDaoConfig.initIdentityScope(type);

        geofenceSmsDaoConfig = daoConfigMap.get(GeofenceSmsDao.class).clone();
        geofenceSmsDaoConfig.initIdentityScope(type);

        geofenceModelDao = new GeofenceModelDao(geofenceModelDaoConfig, this);
        geofenceSmsDao = new GeofenceSmsDao(geofenceSmsDaoConfig, this);

        registerDao(GeofenceModel.class, geofenceModelDao);
        registerDao(GeofenceSms.class, geofenceSmsDao);
    }
    
    public void clear() {
        geofenceModelDaoConfig.getIdentityScope().clear();
        geofenceSmsDaoConfig.getIdentityScope().clear();
    }

    public GeofenceModelDao getGeofenceModelDao() {
        return geofenceModelDao;
    }

    public GeofenceSmsDao getGeofenceSmsDao() {
        return geofenceSmsDao;
    }

}
