package com.doorstop.liz.arrivalnotifier;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table GEOFENCE_MODEL.
 */
public class GeofenceModel {

    private Long id;
    private Double latitude;
    private Double longitude;
    private Float radius;
    private Long expiration;
    private Integer transitionType;

    public GeofenceModel() {
    }

    public GeofenceModel(Long id) {
        this.id = id;
    }

    public GeofenceModel(Long id, Double latitude, Double longitude, Float radius, Long expiration, Integer transitionType) {
        this.id = id;
        this.latitude = latitude;
        this.longitude = longitude;
        this.radius = radius;
        this.expiration = expiration;
        this.transitionType = transitionType;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Double getLatitude() {
        return latitude;
    }

    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    public Double getLongitude() {
        return longitude;
    }

    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    public Float getRadius() {
        return radius;
    }

    public void setRadius(Float radius) {
        this.radius = radius;
    }

    public Long getExpiration() {
        return expiration;
    }

    public void setExpiration(Long expiration) {
        this.expiration = expiration;
    }

    public Integer getTransitionType() {
        return transitionType;
    }

    public void setTransitionType(Integer transitionType) {
        this.transitionType = transitionType;
    }

}
